import{S,i as r,a as q}from"./assets/vendor-xwsNXkQR.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const g=document.querySelector(".loader"),m=document.querySelector(".gallery"),v=new S(".gallery-link",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}),p=document.querySelector(".js-load-more");function h(o){const a=o.map(({webformatURL:t,largeImageURL:i,tags:e,likes:s,views:c,comments:w,downloads:C})=>`
    <li class="gallery-item">
        <a class="gallery-link" href="${i}">
            <img class="gallery-image" src="${t}" alt="${e}" />
        </a>
        <div class="gallery-image-data">
            <p class="data-text"><span class="bold">Likes</span> ${s}</p>
            <p class="data-text"><span class="bold">Views</span> ${c}</p>
            <p class="data-text"><span class="bold">Comments</span> ${w}</p>
            <p class="data-text"><span class="bold">Downloads</span> ${C}</p>
        </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",a),v.refresh()}function x(){r.show({title:"Sorry",message:", there are no images matching your search query. Please try again!",position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"})}function M(){m.innerHTML=""}function y(){g.classList.remove("hidden")}function n(){g.classList.add("hidden")}function k(){p.classList.remove("hidden")}function u(){p.classList.add("hidden")}const P="https://pixabay.com/api/",R="52805725-7d516d36c1804a9cebba9806b";async function b(o,a=1){try{const t=await q(P,{params:{key:R,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:15}});return t.data.hits.length>0?t.data:(x(),[])}catch(t){r.show({message:t.message,position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"})}}const L=document.querySelector(".form"),$=L.querySelector('input[name="search-text"]');L.addEventListener("submit",I);const f=document.querySelector(".js-load-more");f.addEventListener("click",O);u();let l=1,d="";function I(o){if(o.preventDefault(),d=$.value,!d.trim().length){r.show({message:"Input field is empty",position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"}),n();return}M(),y(),l=1,u(),a();async function a(){try{const t=await b(d,l);t.hits.length>0?(h(t.hits),n(),k()):(r.show({message:"Image did not find",position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"}),n())}catch(t){r.show({message:t.message,position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"}),n(),o.target.reset()}finally{n()}}}async function O(){l++,f.disabled=!0;try{y();const o=await b(d,l);n(),h(o.hits);const a=Math.ceil(o.totalHits/o.hits.length);l>=a&&(u(),r.show({message:"We're sorry, but you've reached the end of search results",position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#394becb4"}));const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}catch(o){r.show({message:o.message,position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"})}finally{f.disabled=!1}}
//# sourceMappingURL=index.js.map
