import{S as q,i as r,a as v}from"./assets/vendor-xwsNXkQR.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const g=document.querySelector(".loader"),m=document.querySelector(".gallery"),x=new q(".gallery-link",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}),p=document.querySelector(".js-load-more");function h(s){const a=s.map(({webformatURL:t,largeImageURL:n,tags:e,likes:o,views:i,comments:C,downloads:S})=>`
    <li class="gallery-item">
        <a class="gallery-link" href="${n}">
            <img class="gallery-image" src="${t}" alt="${e}" />
        </a>
        <div class="gallery-image-data">
            <p class="data-text"><span class="bold">Likes</span> ${o}</p>
            <p class="data-text"><span class="bold">Views</span> ${i}</p>
            <p class="data-text"><span class="bold">Comments</span> ${C}</p>
            <p class="data-text"><span class="bold">Downloads</span> ${S}</p>
        </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",a),x.refresh()}function M(){r.show({title:"Sorry",message:", there are no images matching your search query. Please try again!",position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"})}function k(){r.show({message:error.message,position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"})}function I(){m.innerHTML=""}function y(){g.classList.remove("hidden")}function f(){g.classList.add("hidden")}function P(){p.classList.remove("hidden")}function d(){p.classList.add("hidden")}function b(){r.show({message:"We're sorry, but you've reached the end of search results",position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#394becb4"})}const R="https://pixabay.com/api/",$="52805725-7d516d36c1804a9cebba9806b";async function L(s,a=1){try{const t=await v(R,{params:{key:$,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:15}});return t.data.hits.length>0?t.data:(M(),[])}catch(t){r.show({message:t.message,position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"})}}const w=document.querySelector(".form"),E=w.querySelector('input[name="search-text"]');w.addEventListener("submit",O);const u=document.querySelector(".js-load-more");u.addEventListener("click",B);d();let c=1,l="";function O(s){if(s.preventDefault(),l=E.value,!l.trim().length){r.show({message:"Input field is empty",position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"}),f();return}I(),y(),c=1,d(),a();async function a(){try{const t=await L(l,c);t.hits.length>0?(h(t.hits),P()):r.show({message:"Image not found",position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"}),t.hits.length<15&&(d(),b())}catch(t){r.show({message:t.message,position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"}),s.target.reset()}finally{f()}}}async function B(){c++,u.disabled=!0;try{y();const s=await L(l,c);h(s.hits);const a=Math.ceil(s.totalHits/s.hits.length);c>=a&&(d(),b());const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}catch{k()}finally{u.disabled=!1,f()}}
//# sourceMappingURL=index.js.map
