import{S as I,i as n,a as M}from"./assets/vendor-xwsNXkQR.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const p=document.querySelector(".loader"),h=document.querySelector(".gallery"),P=new I(".gallery-link",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}),y=document.querySelector(".js-load-more");function b(s){const t=s.map(({webformatURL:a,largeImageURL:i,tags:e,likes:o,views:c,comments:v,downloads:x})=>`
    <li class="gallery-item">
        <a class="gallery-link" href="${i}">
            <img class="gallery-image" src="${a}" alt="${e}" />
        </a>
        <div class="gallery-image-data">
            <p class="data-text"><span class="bold">Likes</span> ${o}</p>
            <p class="data-text"><span class="bold">Views</span> ${c}</p>
            <p class="data-text"><span class="bold">Comments</span> ${v}</p>
            <p class="data-text"><span class="bold">Downloads</span> ${x}</p>
        </div>
    </li>`).join("");h.insertAdjacentHTML("beforeend",t),P.refresh()}function $(){n.show({title:"Sorry",message:", there are no images matching your search query. Please try again!",position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"})}function R(){h.innerHTML=""}function L(){p.classList.remove("hidden")}function f(){p.classList.add("hidden")}function w(){y.classList.remove("hidden")}function d(){y.classList.add("hidden")}function S(){n.show({message:"We're sorry, but you've reached the end of search results",position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#394becb4"})}function k(){n.show({message:"Image not found",position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"})}function N(){n.show({message:"Input field is empty",position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"})}function C(){n.error({message:"Sorry, something went wrong. Please try again!",position:"topRight"})}const O="https://pixabay.com/api/",B="52805725-7d516d36c1804a9cebba9806b",g=15;async function q(s,t=1){try{const a=await M(O,{params:{key:B,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:g}});return a.data.hits.length>0?a.data:($(),[])}catch(a){n.show({message:a.message,position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"})}}const m=document.querySelector(".form"),E=m.querySelector('input[name="search-text"]');m.addEventListener("submit",j);const u=document.querySelector(".js-load-more");u.addEventListener("click",D);d();let r,l;async function j(s){if(s.preventDefault(),R(),L(),d(),r=1,l=E.value,!l.trim().length){N(),f(),m.reset();return}try{const t=await q(l,r);t.hits.length>0?(b(t.hits),w()):k(),t.hits.length<g&&(d(),S())}catch{C(),s.target.reset()}finally{f()}}async function D(){r++,u.disabled=!0;try{L();const s=await q(l,r);b(s.hits);const t=Math.ceil(s.totalHits/g);r>=t&&(d(),S());const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}catch{r--,w(),C()}finally{u.disabled=!1,f()}}
//# sourceMappingURL=index.js.map
